### ISSUE TITLE
Some checks run for each font but should only run once per family.

### ISSUE THREAD

**Issue by graphicore** [googlefonts/fontbakery#2370] opened 2019-03-05 18:10 UTC
## Observed behaviour

I just discovered that we have some checks that run for each font but that should only run once per family. 

 * **com.google.fonts/check/011** Fonts have equal numbers of glyphs?
 * **com.google.fonts/check/012** Fonts have equal glyph names?

## Expected behaviour

It's unnecessary to run these checks for each font, thus it shouldn't happen. Also, it looks like it is unintentional anyways.

## Resources and exact process needed to replicate

In this case the use of the `@condition is_ttf` is responsible. e.g.:

```py
# specifications/googlefonts.py

@check(
  id = 'com.google.fonts/check/011',
  conditions = ['is_ttf',
                'stylenames_are_canonical']
)
def com_google_fonts_check_011(ttFonts):
  # ...

#specifications/shared_conditions.py

@condition
def is_ttf(ttFont):
  return 'glyf' in ttFont
```

The check itself only needs `ttFonts` but via the `@condition is_ttf` in its `conditions` it runs for each font where that condition is `True` and hence the checkrunner is forced to execute the check once per font.

**Comment by graphicore** [comment] 2019-03-05 18:12
There could be more cases similar to these. I just found these because they were failing in an example I ran. I didn't look into all executed checks (PASS, SKIP, etc.).

**Comment by felipesanches** [comment] 2019-03-05 21:17
I verified all checks that rely on this condition and made sure the problem is fixed in all of them.

**Closed** 2019-03-05 21:17 UTC
