### ISSUE TITLE
FAIL with Fontbakery lastest version although I have the latest version

### ISSUE THREAD

**Issue by RosaWagner** [googlefonts/fontbakery#2953] opened 2020-07-01 12:37 UTC
## Observed behaviour

When I run bakery with gftools from terminal I have this FAIL : 
```
🔥 FAIL: Do we have the latest version of FontBakery installed?
com.google.fonts/check/fontbakery_version

🔥 FAIL Unable to detect what's the latest version of FontBakery available. Maybe we're offline? Please check Internet access and try again.
```

I don't understand why, I have the lastest version. 

Although when I run Fontbakery from the platfrom, this check transform into : 
```
com.google.fonts/check/ftxvalidator_is_available Is the command `ftxvalidator` (Apple Font Tool Suite) available?

WARN Could not find ftxvalidator.
```

I installed ftxvalidator but apparently it doesn't find the path to it, and whatever I have seen in the issues, I don't manage to make it work. I have Mac Mojav 10.14.6 and installed the fontools pack that is supposed to match the OS version.

**Comment by felipesanches** [comment] 2020-07-01 12:43
I'm confused. You mention two different checks here:
* **com.google.fonts/check/fontbakery_version**
* **com.google.fonts/check/ftxvalidator_is_available**

**Comment by RosaWagner** [comment] 2020-07-01 12:46
Sorry, I thought it could highlight a difference of set up, because there are both from the "Family Check", I don't have a ftxvalidator fail when I run FB from the terminal. So I thought it might be linked somehow?

**Comment by felipesanches** [comment] 2020-07-01 13:05
no, these checks are unrelated.

I'll look at these checks implementations to see if I can spot something wrong.

**Comment by graphicore** [comment] 2020-07-01 13:06
> Although when I run Fontbakery from the platform, this check transform into :

@RosaWagner what is "the platform"? Is it Font Bakery Dashboard?

**Comment by RosaWagner** [comment] 2020-07-01 13:08
>Is it Font Bakery Dashboard?

YEP

>no, these checks are unrelated.

Haha Okay ^^ I shall reopen one the related issue then.

**Comment by graphicore** [comment] 2020-07-01 13:11
> > Is it Font Bakery Dashboard?
> YEP

Just FYI, Font Bakery Dashboard runs on the Google Cloud. We don't have (simple) access to MacOS machines from there, so we can't run ftxvalidator, which is Mac only.

**Comment by RosaWagner** [comment] 2020-07-01 13:18
AAAAAH OK, makes sense

**Comment by felipesanches** [comment] 2020-07-10 04:01
I'm closing this one as it seems to be a duplicate of #2966

**Closed by felipesanches** 2020-07-10 04:01 UTC
