### ISSUE TITLE
Update wght named instances check 

### ISSUE THREAD

**Issue by davelab6** [googlefonts/fontbakery#3335] opened 2021-06-09 14:50 UTC
As explained in https://github.com/google/fonts/issues/3453#issuecomment-857761955

- [ ] For static families, any x100 weights within the min-max range that are missing should FAIL. Eg, if range is 400 to 900, and static styles are 400 500 700 900, then 600 and 800 are missing and should FAIL.
- [ ] For VF families, any x100 weight named instances missing from the fvar table should FAIL. 
- [ ] For VF families, any x100 weight named instances missing from the STAT table should FAIL.

**Comment by RosaWagner** [comment] 2021-06-09 15:31
The rationale could advise designer to reduce the range of their axis if it seems that there is not enough space between two instances to add an intermediate one. Except for already published instances — it would create a regression.

Classical cases is ExtraLight: Thin and Light being too close visually for adding an ExtraLight. In that case, we could suggest to reduce the range, Thin would become ExtraLight.

Other classical but tricky case: the need of SemiBold when the range cover until Bold. Here, Medium and Bold are too close visually to add a SemiBold, but the range can't be reduced cause the Bold instance is more important to have because of style linking etc. Then, we have no choice than to change the location of the Medium to make space for a SemiBold, OR to leave it like that and the SemiBold will be kind of useless and absurd (but at least the designer has his Medium where he wants it).

**Comment by davelab6** [comment] 2021-06-10 03:08
Yes - thank you - a part of the rationale for that I've explained here, https://github.com/xotypeco/big_shoulders/issues/36#issuecomment-849072666 - but those common cases are excellent to explain

**Comment by RosaWagner** [comment] 2022-05-27 15:55
We need that in the release 0.8.9

**Comment by felipesanches** [comment] 2022-06-10 08:28
I'm sorry, but I will try to make it happen by 0.8.10

**Comment by RosaWagner** [comment] 2023-05-19 09:59
This proposal has been fixed with the implementation of the axis registry check

**Closed by RosaWagner** 2023-05-19 09:59 UTC
Labels: P1 Quick, Severity 4, Rosalie's priority list
