### ISSUE TITLE
Improve fsType messaging

### ISSUE THREAD

**Issue by davelab6** [googlefonts/fontbakery#2001] opened 2018-08-06 12:28 UTC
## Observed behaviour

https://mobile.twitter.com/justvanrossum/status/989804281648812032

## Expected behaviour

Be more welcoming for people with different politics, and more educational for people who have no idea what the current fstype message actually means (eg link to the old Doctorow Microsoft lecture.)

## Resources and exact process needed to replicate

https://www.theguardian.com/technology/2012/may/03/death-of-drm-good-news

https://craphound.com/msftdrm.txt

**Comment by felipesanches** [comment] 2019-01-18 04:50
This is a duplicate of #1856 and it was fixed back in June 26, 2018.

**Comment by felipesanches** [comment] 2019-01-18 04:50
<img width="559" alt="captura de tela 2019-01-18 as 02 48 41" src="https://user-images.githubusercontent.com/213676/51366280-dd993780-1acb-11e9-83c6-7f9d7ef74382.png">

**Closed** 2019-01-18 04:52 UTC
Labels: P1 Quick
