### ISSUE TITLE
Refactoring check-ttf.py and the web app

### ISSUE THREAD

**Issue by m4rc1e** [googlefonts/fontbakery#1212] opened 2017-02-01 10:41 UTC
Hey @felipesanches,

I have concerns over the size of fontbakery-check-ttf.py. 4,500 lines makes navigating it cumbersome. I can already see several objects which could be moved into their own independent modules. It also concerns me how coupled check-ttf.py is to the webapp. 

Imo, the webapp should use a database, instead of generated json files. The bonus of using a database is we can retrieve old reports much more easily. Apologies if this sounds like sucking eggs.

I understand this is not a 1 or 2 day job. This will involve weeks of work to get right. We're at the stage where FB almost does what we want from the cmdline but is a mile off from being a reliable gatekeeper.

I'm more than happy to write in more details what I would expect.

**Comment by felipesanches** [comment] 2017-02-01 11:01
@m4rc1e Feel free to describe here what you have in mind.

Also, I think this is directly related to #1204

**Comment by felipesanches** [comment] 2017-02-01 11:04
The reason why the webapp is fed with json files is because it is intended to fetch data from distributed git repositories where each font project can update their own check-results (likely in an automated Travis job).

**Comment by m4rc1e** [comment] 2017-02-01 11:08
How can we tell if the family has improved or deteriorated over time? 

Apologies if this is already accounted for. I couldn't find it when skimming the source code.

**Comment by felipesanches** [comment] 2017-02-01 11:40
The burndown chart data can help with that.

There's a script that iteratively navigates the commit history of a given git repo and runs fb_check_ttf on it, generating per-commit entries in the check results json report. It is called fontbakery_gather_burndown_data_from_git.py and was introduced together with some check_ttf changes at https://github.com/googlefonts/fontbakery/pull/1206/commits/744165dc0851e668623e19e6a8fba55f4fada01c

It gives us a grasp of the overall score throughout time. It could be good to track eventual regressions of individual checks, though. That would be a neat (and useful) feature!

**Comment by m4rc1e** [comment] 2017-02-01 11:41
Thank you for the clarification.

**Comment by davelab6** [comment] 2017-02-02 02:14
I had a quick chat with @felipesanches and suggested he consider redis/firebase/etc for storing the json. Using github as the datastore is unwise imho

**Comment by davelab6** [comment] 2017-02-02 02:25
> I have concerns over the size of fontbakery-check-ttf.py. 4,500 lines makes navigating it cumbersome. I can already see several objects which could be moved into their own independent modules. 

I am open to this, but I am not sure it is wise - we had the codebase organized in modules and it was much more cumbersome ;)

I think its very helpful that it is a single file that is *simple*, so that relative newbies facing a traceback/exception know exactly which line to look at, and the flow control of the program is... immanent. 

A code folding editor will roll up those 4,500 lines and make navigation more nimble. 

https://en.wikipedia.org/wiki/Folding_editor

https://en.wikipedia.org/wiki/Code_folding

> It also concerns me how coupled check-ttf.py is to the webapp.

@m4rc1e please explain more about this; I am concerned that you are concerned :) 

Per my brief §3.1 - https://github.com/googlefonts/fontbakery/blob/master/BRIEF.md#31-web-checker - then I think that the web app code should be separate, and as far as I can see, it is all separate, in the `/webapp` directory. 

I updated the README to clarify this (https://github.com/googlefonts/fontbakery/pull/1214) as it was a bit unclear/unstructured.

> Imo, the webapp should use a database, instead of generated json files. The bonus of using a database is we can retrieve old reports much more easily. Apologies if this sounds like sucking eggs.

I had a quick chat with @felipesanches and suggested he consider redis/firebase/etc for storing the json. Using github as the datastore is unwise imho

**Comment by felipesanches** [comment] 2017-02-10 05:22
I'll close this because it's being taken care of at issue #1223

**Comment by davelab6** [comment] 2017-02-10 05:25
Will fontbakery_gather_burndown_data_from_git.py run on all TTF in the repo at each commit? Will it follow git rename commits?

**Comment by felipesanches** [comment] 2017-02-10 05:30
This sounds like a good question, but more appropriate for a fresh new issue.

"gather from git" runs on the cmd-line specified TTF files once per commit.

Shortcomings:
* (A) It does not cover more than one family stored in a single repo.
* (B) It does not follow git renames (I considered implementing that. It would be neat. But I did not think it was the most important thing to do in terms of priorities)

**Comment by felipesanches** [comment] 2017-02-10 05:32
There we go: 
https://github.com/googlefonts/fontbakery/issues/1228

**Closed by felipesanches** 2017-02-10 05:32 UTC
