### ISSUE TITLE
Provide option to list the full glyphs instead of "and X more"

### ISSUE THREAD

**Issue by NightFurySL2001** [googlefonts/fontbakery#3512] opened 2021-11-21 02:48 UTC
Currently on 0.8.4, if the list of glyphs with problem is longer than 10, the list is truncated with "and X more". Exporting to HTML or JSON still maintain the "and X more" truncation. Screenshot below.
![image](https://user-images.githubusercontent.com/33471049/142747362-5f508865-fec6-426d-b359-5dc31c4c39f3.png)
![image](https://user-images.githubusercontent.com/33471049/142747366-7b552286-0762-49cb-b5a0-8f0d048f62dc.png)
![image](https://user-images.githubusercontent.com/33471049/142747372-46219d3c-c5ef-491d-bbf3-6cd6037f3bf5.png)
It would be beneficial to provide an option to list the full affected glyphs so we don't need to separate the font and check multiple times. Maybe -F, --full-list?

**Comment by felipesanches** [comment] 2021-11-23 00:28
This is a duplicate of #3173

**Closed by felipesanches** 2021-11-23 00:28 UTC
Labels: P2 Important
