### ISSUE TITLE
com.google.fonts/check/153  Check for count on ijacute

### ISSUE THREAD

**Issue by davelab6** [googlefonts/fontbakery#2263] opened 2018-12-08 21:02 UTC
https://github.com/google/fonts/pull/1779#issuecomment-445486830 should  be checked for in check 153... reference https://typedrawers.com/discussion/1294/how-do-you-implement-ijacute-and-ijacute

**Comment by simoncozens** [comment] 2023-08-14 14:36
Dupe of #1902, fixed with soft dotting check and shaperglot.

**Closed by simoncozens** 2023-08-14 14:36 UTC
Labels: P2 Important
