### ISSUE TITLE
New check: hhea.caretSlopeRun/Rise

### ISSUE THREAD

**Issue by moontypespace** [googlefonts/fontbakery#3998] opened 2022-12-14 13:15 UTC
## What needs to be checked?

if not is_italic(ttFont):
-> hhea.caretSlopeRun == 0
-> hhea.caretSlopeRise == 1

## Detailed description of the problem 

@koeberlin Mentioned issues with Adobe InDesign, when this is not set correcly.

## Optional fix

if not is_italic(ttFont):
-> hhea.caretSlopeRun == 0
-> hhea.caretSlopeRise == 1

## Resources and exact process needed to replicate

https://learn.microsoft.com/en-us/typography/opentype/spec/hhea#:~:text=int16,0%20for%20vertical.

## Expected Profile

Please suggest in which profile should it be included. (You could inspect the Profiles's list at https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/index.html). Most common are:

- [ ] Vendor-specific: Google Fonts
- [ ] Vendor-specific: Adobe Fonts
- [x] OpenType (requirements imposed by the OpenType specification)
- [ ] Universal (broadly accepted best practices on the type design community)
- [ ] Other:

## Expected Result

Which log result level should it have:

- [x] 🔥 **FAIL** (Something that must be addressed for the propper functioning of the font)
- [] ⚠️ **WARN** (Highlights potential issues that are suggested to address)

## Severity assessment

(On a 1 to 5 level, how "buggy" would the font be considered if not including the aspect checked? Where 1 is something ideal to include but that would not affect the behavior of the font, and 5 is something that could lead to bad performance.)

3

**Comment by RosaWagner** [comment] 2022-12-14 13:24
Check is linked to #3670

**Comment by RosaWagner** [comment] 2022-12-14 14:25
@koeberlin then this check is a duplicate of #3670

**Closed** 2023-03-16 11:01 UTC
Labels: New check proposal, Profile: Universal
