### ISSUE TITLE
com.google.fonts/check/canonical_filename is requiring a wrong name for Italics

### ISSUE THREAD

**Issue by vv-monsalve** [googlefonts/fontbakery#2958] opened 2020-07-07 15:24 UTC
## Observed behaviour

When running FontBakery checks on the font Cabin-Italic[wdth,wght].ttf, I have a Fail with a message that says it must be renamed to 'Cabin-Italic[WIDT,wght].ttf'. Since the axis tag for Width is <wdth> I think this could be a bug in the check.

<details>
<summary>🔥 <b>FAIL:</b> Checking file is named canonically.</summary>

* [com.google.fonts/check/canonical_filename](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/canonical_filename)
<pre>--- Rationale ---

A font&#x27;s filename must be composed in the following manner:
&lt;familyname&gt;-&lt;stylename&gt;.ttf

- Nunito-Regular.ttf,
- Oswald-BoldItalic.ttf

Variable fonts must list the axis tags in alphabetical order in square brackets
and separated by commas:

- Roboto[wdth,wght].ttf
- Familyname-Italic[wght].ttf

</pre>

* 🔥 **FAIL** The file 'Cabin-Italic[wdth,wght].ttf' must be renamed to 'Cabin-Italic[WIDT,wght].ttf' according to the Google Fonts naming policy for variable fonts. [code: bad-varfont-filename]

</details>

## Expected behaviour

Not receiving this Fail if the font is named correctly, or to have better instructions on what would be the canonical name required.

## Resources and exact process needed to replicate

Repository with files to replicate: [https://github.com/vv-monsalve/Cabin/tree/QA-Cabin](https://github.com/vv-monsalve/Cabin/tree/QA-Cabin)
FontBakery report: [https://github.com/vv-monsalve/Cabin/blob/QA-Cabin/fonts/VF/qaCabinVf-it-3.md](https://github.com/vv-monsalve/Cabin/blob/QA-Cabin/fonts/VF/qaCabinVf-it-3.md)

**Comment by felipesanches** [comment] 2020-07-07 17:10
thanks, @vv-monsalve

**Comment by vv-monsalve** [comment] 2020-07-07 17:22
> Since the axis tag for Width is I think this could be a bug in the check.

I just realized I missed "wdht" 😄

**Comment by felipesanches** [comment] 2020-07-10 17:32
we investigated this a bit further today in a video call with @m4rc1e 

He seems to have figured out how to fix the problem, but we were not sure exactly why the bad axis name was being generated by glyphsapp. Maybe a bug in GlyphsApp.

**Comment by vv-monsalve** [comment] 2020-07-10 17:49
I'll replicate what Marc did on the video call and run FB 7.28 again, and I'll let you know then if the Fail is still reported. Hopefully not!

**Comment by felipesanches** [comment] 2020-07-10 21:06
yeah, but it would also be good to figure out what caused the problem, so keep a copy of the problematic file so that we can still try to find out.

**Comment by vv-monsalve** [comment] 2020-07-10 22:54
True, I'll do it.

**Comment by felipesanches** [comment] 2020-07-17 18:00
@m4rc1e, what do you think was the cause of this problem?

**Comment by vv-monsalve** [comment] 2020-07-17 18:08
What was done to solve or prevent this FAIL, both on the video call mentioned above and later when replicating it, was:  deleting the `Axes` of the `Custom Parameter` on the Font Info and then re-add it.

Not anything else than that, the same two axes information was included (Weight, Width), no axis was deleted or added, and it worked.  

This is why we think it could be some sort of bug on Glyphs app.

Source files to replicate are in the folder LegacyFiles on my [QA branch](https://github.com/vv-monsalve/Cabin/tree/QA-Cabin/sources/LegacyFilesWIDT).

**Comment by felipesanches** [comment] 2021-08-23 21:25
The "LegacyFiles" are not available anymore on that branch and I was not able to find them elsewhere. This issue sounds like a GlyphsApp bug and we were not able to find any further info.

I think it is wiser here to simply close this. If the problem resurfaces, then we can investigate further.

**Closed by felipesanches** 2021-08-23 21:25 UTC
Labels: P0 Urgent
