### ISSUE TITLE
fontbakery.yml or similar way to mark checks for downstream runs

### ISSUE THREAD

**Issue by davelab6** [googlefonts/fontbakery#2842] opened 2020-04-20 22:29 UTC
## Observed behaviour

https://github.com/agyeiarcher/Crispy-VF/issues/46 is a design with small descenders, so the current descender length check doesn't make sense. 

## Expected behaviour

I expect a way to best indicate to downstream FB check runs that some checks, like this, should pass (or be skipped)

**Comment by felipesanches** [comment] 2020-04-21 01:42
that's what I did in that same repo here:
https://github.com/agyeiarcher/Crispy-VF/pull/34/files

![Screenshot from 2020-04-20 22-40-59](https://user-images.githubusercontent.com/213676/79815830-102d8200-8358-11ea-8e23-6160e12716ed.png)

Isn't that enough as a mechanism to document disabled checks?

**Comment by felipesanches** [comment] 2020-04-21 01:43
most of these are temporarily disabled. But that first one is permanently disabled with a description of the reasoning as a comment: `"We lack ftxvalidator on Travis"`

**Comment by felipesanches** [comment] 2020-04-22 18:37
I consider this to be a duplicate of #2356

**Closed by felipesanches** 2020-04-22 18:37 UTC
Labels: Blocked - waiting for some feedback
