### ISSUE TITLE
fix "undefined name" errors

### ISSUE THREAD

**Issue by felipesanches** [googlefonts/fontbakery#586] opened 2015-12-03 14:03 UTC
Undefined names cause crashes at runtime. This MUST be fixed.

- [x] ./bakery_cli/fixers.py:120:53: F821 undefined name 'content'
- [x] ./bakery_cli/fixers.py:795:41: F821 undefined name 'family_name'
- [x] ./bakery_cli/fixers.py:796:41: F821 undefined name 'subfamily_name'
- [ ] ./bakery_lint/base.py:34:25: F821 undefined name 'is_protected_type'
- [x] ./bakery_lint/fonttests/test_metadata.py:1110:29: F821 undefined name 'TestCaseOperator'
- [x] ./tools/fontbakery-check-otf.py:50:38: F821 undefined name 'test'

Also, on ./bakery_lint/fonttests/\_\_init\_\_.py, we have:

- [ ] :18:1: F403 'from test_ttf import *' used; unable to detect undefined names
- [ ] :19:1: F403 'from test_metadata import *' used; unable to detect undefined names
- [ ] :20:1: F403 'from test_ufo import *' used; unable to detect undefined names
- [ ] :21:1: F403 'from test_description import *' used; unable to detect undefined names
- [ ] :22:1: F403 'from test_upstream import *' used; unable to detect undefined names

**Comment by davelab6** [comment] 2016-03-16 20:19
@felipesanches how to reproduce these errors?

**Comment by felipesanches** [comment] 2016-03-16 20:24
these were reported by flake8 if I recall correctly.

**Comment by felipesanches** [comment] 2016-03-16 20:27
I think it is likely that some of these were already fixed in recent bugfixes. We could re-run flake8 (but in the v0.1.0 it will likely produce several new undefined errors, given we're stripping out and deleting large chunks of code)

Running flake8 on code from the master branch would be better.

**Comment by davelab6** [comment] 2016-03-16 20:38
Okay, I run flake8 on code from the master branch would be better and updated the tasks; the remaining looks like things we wash away in the rewrite, so closing.

**Closed by davelab6** 2016-03-16 20:38 UTC
