### ISSUE TITLE
monospaced fonts: ERROR    GPOS table lacks kerning information

### ISSUE THREAD

**Issue by graphicore** [googlefonts/fontbakery#1078] opened 2016-09-29 19:27 UTC
With VT323, a proper monospaced design I get:

```
ERROR    GPOS table lacks kerning information
```

But for monospaced fonts, this should be not an error. Rather the invert would be true, if a monospaced font has kerning, something might be wrong.

**Comment by m4rc1e** [comment] 2016-09-29 19:42
Yeah,

On Monospace fonts, I ignore this. Many fonts I've come across which are proportional, do not have kerning. I would make this a warning instead of an error.

**Comment by felipesanches** [comment] 2016-10-03 22:57
i'll treat this as a duplicate of #1086

**Closed by felipesanches** 2016-10-03 22:57 UTC
