### ISSUE TITLE
Accept license files in command line to avoid spurious licensing fails

### ISSUE THREAD

**Issue by davelab6** [googlefonts/fontbakery#1875] opened 2018-05-18 16:22 UTC
Marc ran Grenze through the command line to generate the FB report at https://github.com/Omnibus-Type/Grenze/issues/1 and when he added the OFL.txt to the list of filename args, the check runner did not accept that the license was there. 

However, the drag-and-drop input to the dashboard DOES accept TTFs + OFL + METADATA to do a 'complete' check run.

**Comment by graphicore** [comment] 2018-05-18 22:30
The checks look for the license file in the directory of the fonts, should be the same for cli and drag-and-drop. All files given to drag-and-drop are copied into the same temp-dir in the worker, I'm not sure if the web interface accepts files from different disk locations, but font bakery wouldbn't know the original locations anyways.

**Comment by m4rc1e** [comment] 2018-05-21 07:55
Upstream repos are structured so that the license file is kept in the parent dir. The fonts exist in their own dir.

```
Marc:Grenze marc$ tree
.
├── AUTHORS.txt
├── CONTRIBUTORS.txt
├── FONTLOG.txt
├── OFL.txt
├── README.md
├── Sources
│   ├── Grenze\ Italic.glyphs
│   ├── Grenze.glyphs
│   └── Grenze.png
├── documentation
│   ├── Grenze.pdf
│   └── _Grenze.ai
└── fonts
    ├── gx
    │   ├── GrenzeGX.ttf
    │   └── GrenzeGX_Italic.ttf
    └── ttf
        ├── Grenze-Black.ttf
        ├── Grenze-Bold.ttf
        ├── Grenze-ExtraBold.ttf
        ├── Grenze-ExtraLight.ttf
        ├── Grenze-Light.ttf
        ├── Grenze-Medium.ttf
        ├── Grenze-Regular#1.ttx
        ├── Grenze-Regular#2.ttx
        ├── Grenze-Regular.ttf
        ├── Grenze-Regular.ttx
        ├── Grenze-SemiBold.ttf
        └── Grenze-Thin.ttf

```

**Comment by graphicore** [comment] 2018-05-21 10:39
So, we'll have to change the checks …

I think at some point, for the googlefonts spec, we'll have to add information about which source type we're checking (plus probably also some metadata about the source, that was implied somewhere else). That would then be another CLI-argument, like `--source upstream`.

**Comment by felipesanches** [comment] 2018-11-08 11:31
This is actually the same as #2087 

Closing this one as a duplicate of that.

**Closed by felipesanches** 2018-11-08 11:31 UTC
Labels: P1 Quick
