### ISSUE TITLE
nameID edgecase

### ISSUE THREAD

**Issue by alexeiva** [googlefonts/fontbakery#1096] opened 2016-10-04 16:36 UTC
https://github.com/alexeiva/Arsenal/issues/4

Arsenal is generating this error, although the naming is proper. @m4rc1e rechecked on his machine and confirmed the issue. 

```
Font lacks entry with nameId=17 (TYPOGRAPHIC_SUBFAMILY_NAME)  
ERROR    [FONT_FAMILY_NAME(1):WINDOWS(3)] entry: expected 'Arsenal' but got 'Arsenal Bold'
```

TTFs [here](https://github.com/alexeiva/Arsenal/tree/master/fonts/ttf)

**Comment by davelab6** [comment] 2016-10-04 16:51
No, the naming is wrong; for the RIBBI 4 styles, nameID  1 should be the family name only, and there should not be nameIDs 16 or 17

**Comment by alexeiva** [comment] 2016-10-04 17:13
@davelab6 you are wrong, sir

https://gist.github.com/alexeiva/b3c5c063a3a9cc837d4ec17bf45b94e5

**Comment by alexeiva** [comment] 2016-10-04 17:16
[Arsenal-Bold.TTX](https://gist.github.com/alexeiva/91cd9dcc9619d2aa7f347a195352b5ab)

**Comment by davelab6** [comment] 2016-10-05 03:50
@felipesanches confirmed this

**Comment by felipesanches** [comment] 2016-10-05 19:23
@davelab6 I don't get what you mean by "Felipe confirmed this." I did not confirm this. Also, I tested it in my computer and it works for me.

I can't reproduce this issue. Please reopen if any of you still get it, but then I'll need someone to provide a more detailed description of how to replicate the issue.

**Comment by davelab6** [comment] 2016-10-05 19:33
Sorry I meant that I confirmed this :)

**Comment by davelab6** [comment] 2016-10-05 19:33
@alexeiva are you using the very latest version?

**Comment by felipesanches** [comment] 2016-10-05 21:17
oh! I got it:

```
ERROR    Font lacks entry with nameId=17 (TYPOGRAPHIC_SUBFAMILY_NAME)  
ERROR    [FONT_FAMILY_NAME(1):WINDOWS(3)] entry: expected 'Arsenal' but got 'Arsenal Bold'
```

I don't know why I didn't see it the first time.

So... what is the expected behaviour in this case, @davelab6 ?

**Comment by felipesanches** [comment] 2016-10-05 21:18
Also, there are 2 error messages. Both of them are problematic?

**Comment by felipesanches** [comment] 2016-10-06 01:43
if I understood correctly, the commit above (https://github.com/googlefonts/fontbakery/pull/1101/commits/050da91fe8f9c845526b9492cac3a13594f819b7) fixes the detection of a RIBBI style consequently fixing the first error message, while the second message (expected 'Arsenal' but got 'Arsenal Bold') is actually correct and the font should be fixed in that case. (The reationale is based on Dave's comment here: https://github.com/googlefonts/fontbakery/issues/1096#issuecomment-251445795)

**Comment by davelab6** [comment] 2016-10-06 03:00
I said,

> for the RIBBI 4 styles, nameID 1 should be the family name only

The name table is

**Comment by felipesanches** [comment] 2016-10-06 05:19
I'm sorry that I ended up git tagging fontbakery v0.1.0 and closing the milestone without really fixing this one.

Linux torvalds appologized for "the same" today: https://linux.slashdot.org/story/16/10/05/210227/linus-torvalds-says-buggy-crap-made-it-into-linux-48 :-P

I'll resume work on this issue tomorrow.

**Comment by felipesanches** [comment] 2016-10-07 02:39
Running ttx on Arsenal-BoldItalic.ttf in my local checkout (on git commit 506a7434a411dc9886c50f7b1e863c0b932b8edb) results in this entry in the name table:

```
    <namerecord nameID="1" platformID="3" platEncID="1" langID="0x409">
      Arsenal Bold
    </namerecord>
```

My understanding is that FontBakery correctly reports this as a naming error that should be fixed in the font file.

**Comment by felipesanches** [comment] 2016-10-07 02:42
Do you agree, @alexeiva and @davelab6 ?

**Comment by alexeiva** [comment] 2016-10-07 03:59
Hm, no. Here is what I get when I run ttx on `BoldItalic`

``` 
<namerecord nameID="1" platformID="1" platEncID="0" langID="0x0" unicode="True">
      Arsenal
    </namerecord>
```

running f-b on Arsenal Bold Italic:
```
ERROR    [FONT_FAMILY_NAME(1):WINDOWS(3)] entry: expected 'Arsenal' but got 'Arsenal Bold'  
```

**Comment by felipesanches** [comment] 2016-10-07 04:07
Here I get 2 nameID="1" entries. The good one for plat=MAC(1) **and** the bad one for plat=WIN(3):

```
felipe@guarana:~/devel/github_felipesanches/Arsenal/fonts/ttf (master)*$ ttx -t name Arsenal-BoldItalic.ttf
Dumping "Arsenal-BoldItalic.ttf" to "Arsenal-BoldItalic.ttx"...
Dumping 'name' table...
```

```
    <namerecord nameID="1" platformID="1" platEncID="0" langID="0x0" unicode="True">
      Arsenal
    </namerecord>

    [...]

    <namerecord nameID="1" platformID="3" platEncID="1" langID="0x409">
      Arsenal Bold
    </namerecord>
```

**Comment by felipesanches** [comment] 2016-10-07 04:40
@alexeiva could you please take a second look at your ttx output to make sure you're really missing that second nameID="1" entry? (the important entry is the one with platformID="3")

**Comment by felipesanches** [comment] 2016-10-07 21:44
There's realy nothing I can do here unless someone can provide evidence of an actual bug. The error message clearly states that a bad nameID=1/plat=3 entry was found. Checking with TTX I can see the bad entry is indeed there. The supposedly good entry that @alexeiva said he's got from TTX is plat=1 instead, so perhaps the bad entry (plat=3) is also there further down the TTX file.

I'm pretty sure this is an **invalid** issue so I'll close it. Please only reopen this if strong evidence of an actual fontbakery bug can be provided.

**Comment by alexeiva** [comment] 2016-10-12 05:13
For the record, this error is related to a Glyphs update. 
/cc @schriftgestalt 

Previous versions:
```
<namerecord nameID="1" platformID="3" platEncID="1" langID="0x409">
      Arsenal
    </namerecord>
```

Glyphs Version 2.4b (926):

```
<namerecord nameID="1" platformID="3" platEncID="1" langID="0x409">
      Arsenal Bold
    </namerecord>
```

**Comment by davelab6** [comment] 2016-10-12 06:12
> For the record, this error is related to a Glyphs update. 

YIKES! :(

**Comment by schriftgestalt** [comment] 2016-10-12 18:36
This is not a bug in Glyphs but a misconfiguration. The `Bold Italic` instance has a `Bold` in the link to field. This field should be empty.

**Comment by alexeiva** [comment] 2016-10-12 21:33
Okay. This was an oversight on my part. My apologies. 

Was:
![screen shot 2016-10-12 at 14 28 02](https://cloud.githubusercontent.com/assets/16634089/19328455/8696212a-9088-11e6-976f-923ddd00e70c.png)

Result:

```
<namerecord nameID="1" platformID="3" platEncID="1" langID="0x409">
      Arsenal Bold
    </namerecord>
 ```


Fixed:


![screen shot 2016-10-12 at 14 31 28](https://cloud.githubusercontent.com/assets/16634089/19328475/9cfe6cf6-9088-11e6-84fb-4fd660b5a743.png)


Result:

```
<namerecord nameID="1" platformID="3" platEncID="1" langID="0x409">
      Arsenal
    </namerecord>
 ```

**Comment by m4rc1e** [comment] 2016-10-12 21:39
Hey @alexeiva my [fix_gf_spec](https://github.com/m4rc1e/mf-glyphs-scripts/blob/master/Fixes/fix_gf_spec.py#L83-L84) has this implemented ;)

**Comment by davelab6** [comment] 2016-10-12 21:48
@schriftgestalt 👑

**Comment by schriftgestalt** [comment] 2016-10-12 22:00
Please leave the field empty. `Regular` is inferred.

**Comment by alexeiva** [comment] 2016-10-12 22:28
It's time to coin the term #fontbakeryhack : doing something random for the sake of passing fontbakery

**Comment by felipesanches** [comment] 2016-10-12 22:42
There's no value in "passing fontbakery" other than conforming to the quality standards criteria that FB is built on top of. :-)

Also, it is not really ideal to do "random" tweaks if one does not understand the rationale behind the needed adjustments in the tools.

I understand that this specific issue has lead us to a better understanding of how Glyphs deals with these specific name table entries.

**Comment by alexeiva** [comment] 2016-10-12 23:05
I just inspected the problematic Arsenal sources and regenerated them with Marc's fix gf specs script — it does a fine job, and passes fb.  

Original error was related to a fault in my Italic naming. I had 'instance of Bold' instead if (blank). That is why the Roman file looked fine, and we couldn't figure out the problem.

Thanks everyone for a fun, and educational discussion. 
Now, back to real work. 

Result of Marc's script. The proper way to do it. 
![screen shot 2016-10-12 at 15 49 24](https://cloud.githubusercontent.com/assets/16634089/19330595/3d30303c-9094-11e6-8dbb-1eafaaa12767.png)

Glyphs handbook:
![screen shot 2016-10-12 at 15 49 44](https://cloud.githubusercontent.com/assets/16634089/19330768/35b2a7ee-9095-11e6-9aed-ba70ff290f03.png)

**Comment by alexeiva** [comment] 2016-10-14 05:49
So now for https://github.com/alexeiva/Merriweather I did the style linking as suggested by Dave in https://github.com/davelab6/glyphs-export.

It's a four weight family, and I get this warning for `Merriweather-Black.ttf`:

```
ERROR    fontforge did print these messages to stderr:
Warning: Mac string is a subset of the Windows string in the 'name' table
 for the Family string in the English (US) language.
Warning: Mac and Windows entries in the 'name' table differ for the
 SubFamily string in the language English (US)
 Mac String: Black
Windows String: Regular
```

Am I doing something wrong, or should this be just ignored?

**Comment by davelab6** [comment] 2016-11-17 09:17
@m4rc1e and @felipesanches what is the current status of this

**Comment by davelab6** [comment] 2016-11-21 12:34
@m4rc1e and @felipesanches what is the current status of this

**Comment by felipesanches** [comment] 2016-11-21 12:41
@davelab6 I have to think about it. I'll check it out and provide a status update on this in a while.

**Comment by davelab6** [comment] 2016-11-21 12:50
In this case I will deprioritize this

**Comment by felipesanches** [comment] 2016-11-21 13:01
We inherit a few check routines from FontForge. I'll take a look at these two specific ones pointed out by @alexeiva to make sure what FontForge is validating makes sense in this case. But giving Dave's deprioritization of this, I'll only review this later. (Moving on now to the top-priority milestone 0.2.0 issues :-D)

**Comment by alexeiva** [comment] 2016-11-21 14:59
Makes sense. Not all fonts need to inherit legacy metrics. It is always a
case-to-case basis. For example adding tall Vietnamese glyphs may require
vertical readjustments. Or original metrics may have been set unthoughtful
or incorrect. The glyphs script is a very easy fix, and gfregression tool
is good for diagnosing.

Adding a fontbakery warning that v metrics have diverged from server api
would be a useful option. I would then go to gfregression for examination.

**Comment by davelab6** [comment] 2017-03-15 04:48
I am pretty sure this can be closed; Glyphsapp was generating name tables we didn't like, and it was updated to generate name tables we do like.

**Closed by davelab6** 2017-03-15 04:48 UTC
Labels: P3 Soon, Support
