### ISSUE TITLE
Ignored --autofix in fix-opentype-names.py

### ISSUE THREAD

**Issue by felipesanches** [googlefonts/fontbakery#631] opened 2016-01-19 17:13 UTC
The --autofix argument is never really used in this script...

```python
parser.add_argument('--autofix', action='store_true', help='Apply autofix')
```

**Comment by davelab6** [comment] 2016-01-20 20:25
This seems related to https://github.com/googlefonts/fontbakery/issues/628 and should be combined with that tool. 

Current the tool prints only some of the NAMEIDs...

    $ fontbakery-fix-opentype-names.py ~/fonts/ofl/abyssinicasil/AbyssinicaSIL-Regular.ttf 
    ```
    AbyssinicaSIL-Regular.ttf
    
    NAMEID 1: "Abyssinica SIL Regular"
    NAMEID 2: "Regular"
    NAMEID 4: "Abyssinica SIL Regular"
    NAMEID 6: "AbyssinicaSIL-Regular"
    NAMEID 18: "Abyssinica SIL Regular"
    NAMEID 1: "Abyssinica SIL Regular"
    NAMEID 2: "Regular"
    NAMEID 4: "Abyssinica SIL Regular"
    NAMEID 6: "AbyssinicaSIL-Regular"
    NAMEID 16: "Abyssinica SIL"
    NAMEID 17: "Regular"
    ```
    $

It would be better for it to print all the name IDs, with all the attributes, in a table. 

And then the autofix would drop PID=1 items, and fix up others, so the names are canonical (as listed in https://github.com/googlefonts/gf-docs/blob/master/HowToGenerateWebNativeFonts.md)  and match the other metadata (per https://docs.google.com/spreadsheets/d/1ckHigO7kRxbm9ZGVQwJ6QJG_HjV_l_IRWJ_xeWnTSBg/edit)

**Comment by davelab6** [comment] 2016-01-20 23:54
Hah! This script currently creates a fix file when run plain:
```
$ ls -1 font*
font.ttf
$ fontbakery-fix-nameids.py font.ttf;
$ ls -1 font*
font.ttf
font.ttf.fix
$
```

**Comment by felipesanches** [comment] 2016-01-21 00:08
yeah! That's common behaviour for all fixers that invoke the apply method. This behavious is implemented in the parent Fixer class inherited by all fixers.

**Comment by davelab6** [comment] 2016-01-21 00:11
Is this a recent change you made?

I think the fixers should require opting into creating new files with an arg...

**Comment by felipesanches** [comment] 2016-01-21 00:29
This is old behaviour that was already there before my recent changes.
I can change it, though, if that makes the tool more useful / nicer to use.

**Comment by davelab6** [comment] 2016-01-21 00:40
Hmm. We should sort that out as a sider issue about making all the fb tools work in a uniform way. 

This specific tool seems like a duplicate of `fontbakery-fix-nameids.py` and that one's output is better than this one's I think. To compare:

```
$ fontbakery-fix-nameids.py Fruktur-Regular.ttf
| filename            | id1     | id2     | id4             | id6             |
|:--------------------|:--------|:--------|:----------------|:----------------|
| Fruktur-Regular.ttf | Fruktur | Regular | Fruktur-Regular | Fruktur-Regular |
$
```

Which files (and lines) should I look at to compare the 2 tools?

**Comment by felipesanches** [comment] 2016-01-21 00:59
* tools/fontbakery-fix-nameids.py
* tools/fontbakery-fix-opentype-names.py
* class RemoveNameRecordWithPlatformID_1_Fixer at bakery_cli/fixers.py
* class FamilyAndStyleNameFixer at  bakery_cli/fixers.py

**Comment by davelab6** [comment] 2016-01-21 01:22
Here's an actual request :) 

This output is: 
```
$ fontbakery-fix-nameids.py Fruktur-Regular.ttf
| filename            | id1     | id2     | id4             | id6             |
|:--------------------|:--------|:--------|:----------------|:----------------|
| Fruktur-Regular.ttf | Fruktur | Regular | Fruktur-Regular | Fruktur-Regular |
$
```

should be fixed to

```
$ fontbakery-fix-nameids.py --autofix Fruktur-Regular.ttf
Was

| filename            | id1     | id2     | id4             | id6             |
|:--------------------|:--------|:--------|:----------------|:----------------|
| Fruktur-Regular.ttf | Fruktur | Regular | Fruktur-Regular | Fruktur-Regular |

Fixed to

| filename            | id1     | id2     | id4             | id6             |
|:--------------------|:--------|:--------|:----------------|:----------------|
| Fruktur-Regular.ttf | Fruktur | Regular | Fruktur | Fruktur-Regular |
$
```

**Comment by felipesanches** [comment] 2016-01-21 01:24
hmm... I see. OK, good :-)

**Comment by felipesanches** [comment] 2016-01-21 17:49
The reason for fontbakery-fix-opentype-names.py printing only a subset of the nameids is because the clean_name_values function explicitely filters them. There's no comment in there explaining why. And it is not obvious to me. But here it is:
https://github.com/googlefonts/fontbakery/blob/master/bakery_cli/utils.py#L311

I can make it not filter nameids here. It is only invoked for the opentype names fixer, so there's no potential bad side-effect for this changem if that's what we really want.

**Comment by felipesanches** [comment] 2016-01-21 17:54
well... here's the reason it was filtering out those other values, apparently:

```bash
felipe@guarana:~/devel/github_google/fonts/ofl/abyssinicasil$ fontbakery-fix-opentype-names.py AbyssinicaSIL-Regular.ttf

NAMEID 0: "Copyright (c) 2000-2013 by SIL International. All rights reserved."
NAMEID 1: "Abyssinica SIL Regular"
NAMEID 2: "Regular"
NAMEID 3: "SILInternational: Abyssinica SIL: 2013"
NAMEID 4: "Abyssinica SIL Regular"
NAMEID 5: "Version 1.500"
NAMEID 6: "AbyssinicaSIL-Regular"
NAMEID 7: "Abyssinica SIL is a trademark of SIL International."
NAMEID 8: "SIL International"
NAMEID 9: "Victor Gaultney and Lorna Priest"
NAMEID 10: "Copyright (c) 2000-2013 by SIL International. All rights reserved."
NAMEID 11: "http://scripts.sil.org"
NAMEID 13: "This Font Software is Copyright (c) 2000-2013, SIL International (http://scripts.sil.org/) with Res This Font Software is licensed under the SIL Open Font License, Version 1.1. This license is copied below, and The goals of the Open Font License (OFL) are to stimulate worldwide development of collaborative font projects, to support the font creation efforts of academic and linguistic communities, and to provide a free and open f The OFL allows the licensed fonts to be used, studied, modified and redistributed freely as long as they are not sold by themselves. The fonts, including any derivative works, can be bundled, embedded, redistributed and/or sold with any software provided that any reserved names are not used by derivative works. The fonts and derivatives, however, cannot be released under any other type of license. The requirement for fonts to remain under  "Font Software" refers to the set of files released by the Copyright Holder(s) under this license and clearly  "Original Version" refers to the collection of Font Software components as distributed by the Copyright Holder "Modified Version" refers to any derivative made by adding to, deleting, or substituting -- in part or in whole -- any of the components of the Original Version, by changing formats or by porting the Font Software to a ne "Author" refers to any designer, engineer, programmer, technical writer or other person who contributed to the Permission is hereby granted, free of charge, to any person obtaining a copy of the Font Software, to use, study, copy, merge, embed, modify, redistribute, and sell modified and unmodified copies of the Font Software, sub 1) Neither the Font Software nor any of its individual components, in Original or Modified Versions, may be so 2) Original or Modified Versions of the Font Software may be bundled, redistributed and/or sold with any software, provided that each copy contains the above copyright notice and this license. These can be included either as stand-alone text files, human-readable headers or in the appropriate machine-readable metadata fields withi 3) No Modified Version of the Font Software may use the Reserved Font Name(s) unless explicit written permission is granted by the corresponding Copyright Holder. This restriction only applies to the primary font name as  4) The name(s) of the Copyright Holder(s) or the Author(s) of the Font Software shall not be used to promote, endorse or advertise any Modified Version, except to acknowledge the contribution(s) of the Copyright Holder(s) 5) The Font Software, modified or unmodified, in part or in whole, must be distributed entirely under this license, and must not be distributed under any other license. The requirement for fonts to remain under this licen THE FONT SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO ANY WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT OF COPYRIGHT, PATENT, TRADEMARK, OR OTHER RIGHT. IN NO EVENT SHALL THE COPYRIGHT HOLDER BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, INCLUDING ANY GENERAL, SPECIAL, INDIRECT, INCIDENTAL, OR CONSEQUENTIAL DAMAGES, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF THE USE OR INABILITY TO USE THE FONT SOFTWARE OR FROM OTHER DEALINGS IN THE FONT SOFTWARE."
NAMEID 14: "http://scripts.sil.org/OFL"
NAMEID 18: "Abyssinica SIL Regular"
NAMEID 256: "Punctuation"
NAMEID 257: "Ethiopic-style"
NAMEID 258: "Latin-style"
NAMEID 259: "mwa alternates"
NAMEID 260: "Standard"
NAMEID 261: "Alternate-1"
NAMEID 262: "Alternate-2"
NAMEID 263: "rwa alternate"
NAMEID 264: "Alternate"
NAMEID 265: "Standard"
NAMEID 266: "xoa alternate"
NAMEID 267: "Standard"
NAMEID 268: "Alternate"
NAMEID 269: "xwa alternates"
NAMEID 270: "Standard"
NAMEID 271: "Handwriting"
NAMEID 272: "nwa alternate"
NAMEID 273: "Alternate"
NAMEID 274: "Standard"
NAMEID 275: "nya alternates"
NAMEID 276: "Disconnected"
NAMEID 277: "Standard"
NAMEID 278: "nywa alternates"
NAMEID 279: "Standard"
NAMEID 280: "Cohen"
NAMEID 281: "Disconnected"
NAMEID 282: "kxwaa alternate"
NAMEID 283: "Alternate"
NAMEID 284: "Standard"
NAMEID 285: "zha alternates"
NAMEID 286: "Cohen"
NAMEID 287: "Chaine"
NAMEID 288: "Standard"
NAMEID 289: "dda alternates"
NAMEID 290: "Alternate"
NAMEID 291: "Standard"
NAMEID 292: "gwaa alternates"
NAMEID 293: "Alone Stokes"
NAMEID 294: "Standard"
NAMEID 295: "Sebat Bet"
NAMEID 296: "gga alternates"
NAMEID 297: "Standard"
NAMEID 298: "Disconnected"
NAMEID 299: "ggwaa alternate"
NAMEID 300: "Standard"
NAMEID 301: "Disconnected"
NAMEID 302: "phe alternate"
NAMEID 303: "Standard"
NAMEID 304: "Alternate"
NAMEID 305: "tswa alternate"
NAMEID 306: "Standard"
NAMEID 307: "Alternate"
NAMEID 308: "fwa alternates"
NAMEID 309: "Standard"
NAMEID 310: "Cohen-1"
NAMEID 311: "Cohen-2"
NAMEID 312: "rya alternate"
NAMEID 313: "Alternate"
NAMEID 314: "Standard"
NAMEID 315: "mya alternate"
NAMEID 316: "Standard"
NAMEID 317: "Alternate"
NAMEID 318: "mwi alternates"
NAMEID 319: "Sebat Bet"
NAMEID 320: "Standard"
NAMEID 321: "Leslau"
NAMEID 322: "mwe alternates"
NAMEID 323: "Standard"
NAMEID 324: "Leslau"
NAMEID 325: "Sebat Bet"
NAMEID 326: "bwe alternate"
NAMEID 327: "Standard"
NAMEID 328: "Alternate"
NAMEID 329: "fwee alternate"
NAMEID 330: "Standard"
NAMEID 331: "Alternate"
NAMEID 332: "fwe alternate"
NAMEID 333: "Alternate"
NAMEID 334: "Standard"
NAMEID 335: "pwe alternate"
NAMEID 336: "Alternate"
NAMEID 337: "Standard"
NAMEID 338: "ggwa alternates"
NAMEID 339: "Disconnected"
NAMEID 340: "Standard"
NAMEID 341: "3rd form alternates"
NAMEID 342: "Alternate"
NAMEID 343: "Standard"
NAMEID 344: "6th form alternates"
NAMEID 345: "Alternate"
NAMEID 346: "Standard"
NAMEID 347: "NoName"
NAMEID 0: "Copyright (c) 2000-2013 by SIL International. All rights reserved."
NAMEID 1: "Abyssinica SIL Regular"
NAMEID 2: "Regular"
NAMEID 3: "SILInternational: Abyssinica SIL: 2013"
NAMEID 4: "Abyssinica SIL Regular"
NAMEID 5: "Version 1.500"
NAMEID 6: "AbyssinicaSIL-Regular"
NAMEID 7: "Abyssinica SIL is a trademark of SIL International."
NAMEID 8: "SIL International"
NAMEID 9: "Victor Gaultney and Lorna Priest"
NAMEID 10: "Copyright (c) 2000-2013 by SIL International. All rights reserved."
NAMEID 11: "http://scripts.sil.org"
NAMEID 13: "This Font Software is Copyright (c) 2000-2013, SIL International (http://scripts.sil.org/) with Res This Font Software is licensed under the SIL Open Font License, Version 1.1. This license is copied below, and The goals of the Open Font License (OFL) are to stimulate worldwide development of collaborative font projects, to support the font creation efforts of academic and linguistic communities, and to provide a free and open f The OFL allows the licensed fonts to be used, studied, modified and redistributed freely as long as they are not sold by themselves. The fonts, including any derivative works, can be bundled, embedded, redistributed and/or sold with any software provided that any reserved names are not used by derivative works. The fonts and derivatives, however, cannot be released under any other type of license. The requirement for fonts to remain under  "Font Software" refers to the set of files released by the Copyright Holder(s) under this license and clearly  "Original Version" refers to the collection of Font Software components as distributed by the Copyright Holder "Modified Version" refers to any derivative made by adding to, deleting, or substituting -- in part or in whole -- any of the components of the Original Version, by changing formats or by porting the Font Software to a ne "Author" refers to any designer, engineer, programmer, technical writer or other person who contributed to the Permission is hereby granted, free of charge, to any person obtaining a copy of the Font Software, to use, study, copy, merge, embed, modify, redistribute, and sell modified and unmodified copies of the Font Software, sub 1) Neither the Font Software nor any of its individual components, in Original or Modified Versions, may be so 2) Original or Modified Versions of the Font Software may be bundled, redistributed and/or sold with any software, provided that each copy contains the above copyright notice and this license. These can be included either as stand-alone text files, human-readable headers or in the appropriate machine-readable metadata fields withi 3) No Modified Version of the Font Software may use the Reserved Font Name(s) unless explicit written permission is granted by the corresponding Copyright Holder. This restriction only applies to the primary font name as  4) The name(s) of the Copyright Holder(s) or the Author(s) of the Font Software shall not be used to promote, endorse or advertise any Modified Version, except to acknowledge the contribution(s) of the Copyright Holder(s) 5) The Font Software, modified or unmodified, in part or in whole, must be distributed entirely under this license, and must not be distributed under any other license. The requirement for fonts to remain under this licen THE FONT SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO ANY WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT OF COPYRIGHT, PATENT, TRADEMARK, OR OTHER RIGHT. IN NO EVENT SHALL THE COPYRIGHT HOLDER BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, INCLUDING ANY GENERAL, SPECIAL, INDIRECT, INCIDENTAL, OR CONSEQUENTIAL DAMAGES, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF THE USE OR INABILITY TO USE THE FONT SOFTWARE OR FROM OTHER DEALINGS IN THE FONT SOFTWARE."
NAMEID 14: "http://scripts.sil.org/OFL"
NAMEID 256: "Punctuation"
NAMEID 257: "Ethiopic-style"
NAMEID 258: "Latin-style"
NAMEID 259: "mwa alternates"
NAMEID 260: "Standard"
NAMEID 261: "Alternate-1"
NAMEID 262: "Alternate-2"
NAMEID 263: "rwa alternate"
NAMEID 264: "Alternate"
NAMEID 265: "Standard"
NAMEID 266: "xoa alternate"
NAMEID 267: "Standard"
NAMEID 268: "Alternate"
NAMEID 269: "xwa alternates"
NAMEID 270: "Standard"
NAMEID 271: "Handwriting"
NAMEID 272: "nwa alternate"
NAMEID 273: "Alternate"
NAMEID 274: "Standard"
NAMEID 275: "nya alternates"
NAMEID 276: "Disconnected"
NAMEID 277: "Standard"
NAMEID 278: "nywa alternates"
NAMEID 279: "Standard"
NAMEID 280: "Cohen"
NAMEID 281: "Disconnected"
NAMEID 282: "kxwaa alternate"
NAMEID 283: "Alternate"
NAMEID 284: "Standard"
NAMEID 285: "zha alternates"
NAMEID 286: "Cohen"
NAMEID 287: "Chaine"
NAMEID 288: "Standard"
NAMEID 289: "dda alternates"
NAMEID 290: "Alternate"
NAMEID 291: "Standard"
NAMEID 292: "gwaa alternates"
NAMEID 293: "Alone Stokes"
NAMEID 294: "Standard"
NAMEID 295: "Sebat Bet"
NAMEID 296: "gga alternates"
NAMEID 297: "Standard"
NAMEID 298: "Disconnected"
NAMEID 299: "ggwaa alternate"
NAMEID 300: "Standard"
NAMEID 301: "Disconnected"
NAMEID 302: "phe alternate"
NAMEID 303: "Standard"
NAMEID 304: "Alternate"
NAMEID 305: "tswa alternate"
NAMEID 306: "Standard"
NAMEID 307: "Alternate"
NAMEID 308: "fwa alternates"
NAMEID 309: "Standard"
NAMEID 310: "Cohen-1"
NAMEID 311: "Cohen-2"
NAMEID 312: "rya alternate"
NAMEID 313: "Alternate"
NAMEID 314: "Standard"
NAMEID 315: "mya alternate"
NAMEID 316: "Standard"
NAMEID 317: "Alternate"
NAMEID 318: "mwi alternates"
NAMEID 319: "Sebat Bet"
NAMEID 320: "Standard"
NAMEID 321: "Leslau"
NAMEID 322: "mwe alternates"
NAMEID 323: "Standard"
NAMEID 324: "Leslau"
NAMEID 325: "Sebat Bet"
NAMEID 326: "bwe alternate"
NAMEID 327: "Standard"
NAMEID 328: "Alternate"
NAMEID 329: "fwee alternate"
NAMEID 330: "Standard"
NAMEID 331: "Alternate"
NAMEID 332: "fwe alternate"
NAMEID 333: "Alternate"
NAMEID 334: "Standard"
NAMEID 335: "pwe alternate"
NAMEID 336: "Alternate"
NAMEID 337: "Standard"
NAMEID 338: "ggwa alternates"
NAMEID 339: "Disconnected"
NAMEID 340: "Standard"
NAMEID 341: "3rd form alternates"
NAMEID 342: "Alternate"
NAMEID 343: "Standard"
NAMEID 344: "6th form alternates"
NAMEID 345: "Alternate"
NAMEID 346: "Standard"
NAMEID 347: "NoName"
NAMEID 16: "Abyssinica SIL"
NAMEID 17: "Regular"
```

**Comment by felipesanches** [comment] 2016-01-21 19:04
It was filtering so that it would only show the following values: [1, 2, 4, 6, 16, 17, 18]
These correspond to:

* 1: Font Family name
* 2: Font Subfamily name
* 4: Full font name
* 6: Postscript name for the font
* 16: Typographic Family name
* 17: Typographic Subfamily name
* 18: Compatible Full (Macintosh only); On the Macintosh, the menu name is constructed using the FOND resource. This usually matches the Full Name. If you want the name of the font to appear differently than the Full Name, you can insert the Compatible Full Name in ID 18.

**Closed** 2016-03-18 05:44 UTC
