### ISSUE TITLE
Checks for whatever Firefox 54.0a2 (2017-04-04) Dev Ed cares about

### ISSUE THREAD

**Issue by davelab6** [googlefonts/fontbakery#1276] opened 2017-04-12 17:59 UTC
> A LOT of fonts #notworking in #Firefox 54.0a2 (2017-04-04) Dev Ed on #MacOS

\- https://twitter.com/mikhey786/status/849368617389096963

We should have checks for whatever Firefox 54.0a2 (2017-04-04) Dev Ed is failing our fonts on, and urgently prioritize shipping those fixes :)

**Comment by felipesanches** [comment] 2017-04-12 19:01
OK. I asked for further user feedback about the issue there:
* https://twitter.com/juca_gnu/status/852233351167606786
* https://twitter.com/juca_gnu/status/852233987271663616

**Comment by davelab6** [comment] 2017-04-13 22:34
https://twitter.com/thisisclayton/status/852523836994146305 related

**Comment by mikhey** [comment] 2017-04-13 23:09
Here's how the site looks when I load it up:

https://twitter.com/mikhey786/status/852509976593608704

![screen shot 2017-04-13 at 9 12 07 am](https://cloud.githubusercontent.com/assets/449275/25027687/9f3cec34-207c-11e7-8dfc-1e7648f8dcfb.png)

**Comment by felipesanches** [comment] 2017-04-18 05:13
@davelab6 I have the impression that FontBakery already has got code for detecting this issue, since we have a  ot-sanitiser checker. I downloaded the font and tested it with ots manually (on the command line) and I could reproduce the exact same error message.

**Comment by felipesanches** [comment] 2017-04-28 15:35
Do we have any further info about this one?

If the bundled otsanitise on Firefox is the source of the error messages, then fontbakery already detects the exact same issues with our otsanitise check. Unless I missed something, I think it is safe to close this issue, as we already detect such problems in the fonts being tested by fontbakery.

**Closed by felipesanches** 2017-04-28 15:35 UTC
Labels: P0 Urgent
