### ISSUE TITLE
Verify name table checks work

### ISSUE THREAD

**Issue by davelab6** [googlefonts/fontbakery#2910] opened 2020-06-04 13:54 UTC
## Observed behaviour

A user wrote me,

> Hi! I was working with Manrope (variable font) and I have problems with Adobe XD (always shows me "Regular" weight). Finally, I realized that the problem is : separate weights files, are the same. My solution was download the font from FontSquirrel, and works without problems.
> 
> So, please, can you review the separate weights version of variable fonts? I was reading on forums, and other people write about the same situation, but with other variable fonts.
> 
> Thanks in advance!

## Expected behaviour

FontBakery name checks should identify the problems with the static fonts in the fonts.google.com/download?family=Manrope ZIP.

Is this the case?

**Comment by thlinard** [comment] 2020-06-04 20:20
Probably a duplicate of #2430 (nameID 3 is wrong with the static Manrope files downloaded on https://fonts.google.com/specimen/Manrope, but the static files here are good).

There may be other problems than nameID 3, I haven't done an extensive study (my teams only use the static files from this repo, and they are fine).

**Comment by m4rc1e** [comment] 2020-06-16 09:28
Not updating nameID 3 is a bug. I've pinged the engineers to let them know.

**Comment by felipesanches** [comment] 2020-06-29 02:21
(see also: #2945)

**Comment by simoncozens** [comment] 2023-08-14 10:00
I'm not sure there's anything left to look at here, given #2430.

**Closed by simoncozens** 2023-08-14 10:00 UTC
