### ISSUE TITLE
TRACEBACK Failure to generate ghmarkdown for Unna

### ISSUE THREAD

**Issue by m4rc1e** [googlefonts/fontbakery#2194] opened 2018-11-13 16:05 UTC
Tried to Generate a markdown report for the following PR, https://github.com/Omnibus-Type/Unna/pull/6

CLI input:
```
fontbakery check-googlefonts ~/Documents/googlefonts/manual_font_cleaning/Unna/fonts/ttf/*.ttf --ghmarkdown ~/Desktop/Unna.md
```

Traceback:
```
Traceback (most recent call last):
  File "/Users/marc/Documents/googlefonts/fontbakery/venv_dev/bin/fontbakery", line 9, in <module>
    load_entry_point('fontbakery==0.5.1.dev28+g39c4540c', 'console_scripts', 'fontbakery')()
  File "/Users/marc/Documents/googlefonts/fontbakery/Lib/fontbakery/cli.py", line 22, in main
    "fontbakery.commands." + subcommand_module, run_name='__main__')
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 208, in run_module
    return _run_code(code, {}, init_globals, run_name, mod_spec)
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/marc/Documents/googlefonts/fontbakery/Lib/fontbakery/commands/check_googlefonts.py", line 28, in <module>
    sys.exit(main())
  File "/Users/marc/Documents/googlefonts/fontbakery/Lib/fontbakery/commands/check_specification.py", line 287, in main
    args.ghmarkdown.write(mdr.get_markdown())
  File "/Users/marc/Documents/googlefonts/fontbakery/Lib/fontbakery/reporters/ghmarkdown.py", line 87, in get_markdown
    "".join(map(self.check_md, family_checks)) + "<br>")
  File "/Users/marc/Documents/googlefonts/fontbakery/Lib/fontbakery/reporters/ghmarkdown.py", line 44, in check_md
    checkid = check["key"][1].split(":")[1].split(">")[0]
IndexError: list index out of range
```

Fontbakery version 0.5.1.dev28+g39c4540c

**Comment by graphicore** [comment] 2018-11-13 16:16
This is related #2167 CC @madig

**Comment by graphicore** [comment] 2018-11-13 16:20
At least it looks related. But the Font Bakery version seems too old. Is #2167 already merged in your version?

**Comment by m4rc1e** [comment] 2018-11-13 16:25
Just updated my FB to 0.5.1.dev173+gd1d32044.d20181113 and it still has the same issue.

**Comment by graphicore** [comment] 2018-11-13 16:38
@m4rc1e haha, do you know if it was merged/active in your `Fontbakery version 0.5.1.dev28+g39c4540c` looks like 39c4540c was from September 1st.

**Comment by m4rc1e** [comment] 2018-11-13 16:41
@graphicore It's completely bizzare. I've always installed FB using `pip install -e .` I pull it at least once a day as well. If you do `fontbakery --version` what do you get?

**Comment by graphicore** [comment] 2018-11-13 16:55
I'm guessing `fontbakery --version` will give you the point when you last `did pip install -e .`, regardless of when you last fetched the latest upstream ... checking ...

```
commander@ghoul:~/Projekte/googlefonts/fontbakery$ . venv/bin/activate
(venv) commander@ghoul:~/Projekte/googlefonts/fontbakery$ fontbakery --version
0.5.2.dev86+gf6ecb52f
(venv) commander@ghoul:~/Projekte/googlefonts/fontbakery$ git fetch upstream 
(venv) commander@ghoul:~/Projekte/googlefonts/fontbakery$ git rebase upstream/master 
Current branch master is up to date.
(venv) commander@ghoul:~/Projekte/googlefonts/fontbakery$ pip install -e .
Obtaining file:///home/commander/Projekte/fontdev/googlefonts/fontbakery
[… shortened for readability …]
Successfully installed fontbakery
(venv) commander@ghoul:~/Projekte/googlefonts/fontbakery$ fontbakery --version
0.6.2.dev1+gd1d32044
```

Yes, my guessing seems confirmed. :-D

**Comment by davelab6** [comment] 2018-11-13 18:19
> Just updated my FB to 0.5.1.dev173+gd1d32044.d20181113 and it still has the same issue.

That seems very old!

**Comment by m4rc1e** [comment] 2018-11-14 13:10
@davelab6 @graphicore surely this means the `fontbakery --version` is broken if it's only displaying the last time a user installed it?

I'm certain I was on the latest version.

**Comment by graphicore** [comment] 2018-11-14 13:11
It's related to PIP, as I showed above.

**Comment by madig** [comment] 2018-11-14 13:12
We use setuptools_scm, which generates the _version.py file with the
current tag/commit id at install time.

**Comment by graphicore** [comment] 2018-11-14 13:33
> This is a bug imo.

Until there's someone fixing it, I suggest using in one go `git pull;pip install -e .;`. Trying to fixi this in `fontbakery --version` could become dirty. Also, `pip install -e .` could be considered a special case.

**Comment by m4rc1e** [comment] 2018-11-14 13:34
Thanks @graphicore! I'll do this moving forward. I'll file a seperate issue for this.

**Comment by m4rc1e** [comment] 2018-11-21 12:14
Could we prioritise this?

MD generation is still broken for all fonts.

**Comment by thundernixon** [comment] 2018-11-21 22:53
Running into this same issue on the latest release and on a git pull with `pip install -e .`. 

Thanks for filing the issue, @m4rc1e!

**Comment by felipesanches** [comment] 2018-11-23 04:13
OK. For now I will just revert PR #2167 and then if this is strictly needed for @madig then we can give it a second chance later taking care of not breaking other things.

**Closed** 2018-11-23 04:29 UTC
Labels: P0 Urgent
