### ISSUE TITLE
com.google.fonts/check/name/rfn

### ISSUE THREAD

**Issue by twardoch** [googlefonts/fontbakery#3768] opened 2022-05-09 16:01 UTC
https://github.com/google/fonts/pull/4615

lists

> FAIL: Name table strings must not contain the string 'Reserved Font Name'. ([com.google.fonts/check/name/rfn](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/name/rfn))

The check is not smart. GF may wish to onboard a font that had originally been originally published with an RFN but then renamed. This is the case here:

> Copyright 2015-2022 The Aref Ruqaa Project Authors (https://github.com/aliftype/aref-ruqaa), with Reserved Font Name EURM10.

The RFN needs to be mentioned in the font. But if the font does not use that RFN in its names, I don’t see why there should be a problem.

**Comment by khaledhosny** [comment] 2022-05-09 19:33
Duplicate of #3739

**Comment by felipesanches** [comment] 2022-05-09 19:41
thanks, @khaledhosny

**Closed by felipesanches** 2022-05-09 19:41 UTC
