### ISSUE TITLE
Add check for Small Cap siblings

### ISSUE THREAD

**Issue by davelab6** [googlefonts/fontbakery#2340] opened 2019-02-08 00:38 UTC
## Observed behaviour

We should have a Small Cap (SC) generator checker that goes over all the fonts in the repo, finds ones with SMCP OT code, and generates SC sibling families, and checks if the SC fonts are the same as the generated ones, and if not, warns. 

This is maybe not needed in the regular everyday check profile, but is something that is needed less frequently until it passes, and then needs to become a fail to stop regressions.

We should also have a check that all SC sibling families have a parent with SC included as SMCP glyphs + code...

**Comment by felipesanches** [comment] 2020-02-13 22:46
This is a duplicate of #1568

**Closed by felipesanches** 2020-02-13 22:46 UTC
Labels: P2 Important
