### ISSUE TITLE
Do not run UFO checks on non-ufo files

### ISSUE THREAD

**Issue by davelab6** [googlefonts/fontbakery#424] opened 2014-09-29 17:00 UTC
Do not run UFO checks on non-ufo files. These checks aren't needed and slow the process down:

```
git clone git@github.com:fontdirectory/GUPTER.git;
cd GUPTER;
fontbakery .;
$ bakery-lint.py upstream Gupter-Bold.otf
...
bakery_lint.tests.upstream.test_check_ufo_……..
```

**Comment by davelab6** [comment] 2016-02-02 00:48
@felipesanches you had mentioned seeing this lately. Confirmed?

**Comment by felipesanches** [comment] 2016-02-02 00:51
yeah! This is a duplicate of https://github.com/googlefonts/fontbakery/issues/623 (or vice-versa ;-D)

**Closed** 2016-03-16 03:58 UTC
Labels: P1 Quick
