### ISSUE TITLE
Bogus handling version name id

### ISSUE THREAD

**Issue by khaledhosny** [googlefonts/fontbakery#797] opened 2016-05-28 01:21 UTC
The code in [fontbakery-check-ttf.py:833](https://github.com/googlefonts/fontbakery/blob/master/fontbakery-check-ttf.py#L833) removes version name ids, then in [fontbakery-check-ttf.py:1202](https://github.com/googlefonts/fontbakery/blob/master/fontbakery-check-ttf.py#L1202) it complains that the name (that it removed and is now getting `False` instead) is not correct.

**Comment by davelab6** [comment] 2016-05-28 01:49
Yeah, that name table thing is bad. https://github.com/davelab6/glyphs-export has name tables as I think they should be set up. What do you think? :)

What are your recommendations for vertical metrics?

**Comment by khaledhosny** [comment] 2016-05-28 15:42
https://github.com/davelab6/glyphs-export has lots of platformID=1 names, other than dropping those it sounds fine.

I have no general formula for vertical metrics, I usually start with font bbox plus some offset, but for fonts that stack vertically (e.g. Aref Ruqaa) this will be too small, for other fonts there might be some too big glyphs that are not commonly used so bbox is too much. I think it should be left to the designer to make the judgment here, any automatic override will be problematic (not to mention the Win metrics fiasco).

**Comment by davelab6** [comment] 2016-05-28 15:48
@felipesanches Rod is going to make a name table checker that confirms to those files, so no need to duplicate the effort.

**Comment by felipesanches** [comment] 2016-05-28 15:50
ok, thanks

**Comment by richardfink** [comment] 2016-05-29 15:23
> I have no general formula for vertical metrics,

Me neither except that I almost always look at the font as a webfont in a
browser to:
1)  check for any clipping
 2) confirm that hen the CSS line height is set to the default "normal" (I
set it explicitly to that in my test pages.) - the spacing in between lines
looks like what happens with the web safe system fonts we've all grown to
know and grow bored with.

However, there might be some extremes - some outer boundaries that should
not be crossed that it might pay to check. Gotta think about that.

I haven't reviewed the changes made by Felipe yet but I'll probably have
more to say about this later.

- rich

**Comment by davelab6** [comment] 2016-05-31 17:57
Actually, please @felipesanches do write a checker to conform name tables to https://github.com/davelab6/glyphs-export  :)

**Comment by davelab6** [comment] 2016-07-06 22:48
Closing as a duplicate of #545

**Closed by davelab6** 2016-07-06 22:48 UTC
Labels: P0 Urgent
