### ISSUE TITLE
check-ttf.py: ERROR    More than a single license file found. Please review.

### ISSUE THREAD

**Issue by m4rc1e** [googlefonts/fontbakery#1379] opened 2017-06-06 16:29 UTC
Got this error with this folder structure:
![screen shot 2017-06-06 at 17 27 53](https://user-images.githubusercontent.com/7525512/26840299-95e30b92-4add-11e7-8e54-9ecb60cc1393.png)

I haven't had time to look at the implementation but I reckon its counting other .txt files as license files, possibly the FONTLOG.txt.

**Comment by davelab6** [comment] 2017-06-15 02:23
Sounds good, @felipesanches please fix :)

**Comment by felipesanches** [comment] 2017-06-21 00:52
The check only looks for OFL.txt or LICENSE.txt, so there's absolutely no change of it mistakenly interpreting FONTLOG.txt as a license file.

I think that the reason for this bad behaviour is the change introduced at https://github.com/googlefonts/fontbakery/commit/956122dccb949b70204887019b8783838077303c to address the following request from Dave on issue #1270:

```
"Check font has a license, should look for OFL.txt or LICENSE.txt file in the
 directory of the fonts and the root directory; 
https://github.com/googlefonts/abeezee/blob/master/OFL.txt
 exists so this shouldn't error"
```

So, it may be finding a source file in the working directory at which @m4rc1e is invoking fontbakery.

**Comment by felipesanches** [comment] 2017-06-21 00:55
I'm refering to this code snippet:

```python
    # Also try at the current working dir:
    elif os.path.exists(license):
      if found is not False:
        fb.error("More than a single license file found."
                 " Please review.")
        found = "multiple"
```

**Comment by felipesanches** [comment] 2017-06-21 01:40
By the way... I did not like adding this, back then. Exactly because it can lead to this kind of situation in which the behaviour is not obvious to the user.

We may fix this reverting that change. But then it would be good to have an alternative solution to the case @davelab6 originally wanted to address. That is, to make the check a bit more flexible in order to not fail when evaluating font project directory structures in which the license file is in the root of the git repo, instead of being placed in the same directory as the resto of the TTF files.

**Comment by davelab6** [comment] 2017-06-21 02:03
If found is multiple, warn instead of error

**Comment by felipesanches** [comment] 2017-06-21 02:10
ok, cool! That sounds reasonable. I'll change it to a warning, then.

**Comment by felipesanches** [comment] 2017-06-21 03:06
@m4rc1e I changed the errors into warnings. But also tried to make the user aware of what the problem is. Can you please verify whether that works better for you or if you'd have any other suggestion?

Otherwise, consider closing the issue whenever you're happy about it.

cheers!

**Comment by felipesanches** [comment] 2017-07-09 15:08
> Otherwise, consider closing the issue whenever you're happy about it.

Alternatively... reopen if unhappy ;-)

**Closed by felipesanches** 2017-07-09 15:08 UTC
Labels: P1 Quick
