### ISSUE TITLE
Vertical metrics must be consistent in superfamilies

### ISSUE THREAD

**Issue by davelab6** [googlefonts/fontbakery#1487] opened 2017-08-04 14:40 UTC
The vertical metrics of these 2 families should be identical, 

https://fonts.google.com/specimen/Archivo
https://fonts.google.com/specimen/Archivo+Narrow

But they aren't. This suggests to me that there is a class of font bakery checks missing for 'super families' to keep them consistent. We now have quite a few super families, typically with different widths, but also different optical sizes (eg "Something Sans" and "Something Sans Display" or "Something Sans Micro") 

![animatespheres](https://user-images.githubusercontent.com/261579/28973575-9fb50736-7901-11e7-8a01-d8b92b57d5da.gif)

Should be

![archivomatches-01](https://user-images.githubusercontent.com/261579/28973584-a6e688ea-7901-11e7-8273-bf2e5f5cd474.png)

**Comment by Omnibus-Type** [comment] 2017-08-04 15:17
Hi! About Archivo and Archivo Narrow vMetrics, please note that they must also match with Archivo Black vMetrics…

**Comment by m4rc1e** [comment] 2017-08-04 16:29
@Omnibus-Type thanks for adding that info.

I'm in two minds about this. I agree that every super family should have consistent vertical metrics. However, this is not really possible if the fonts have already been released and have differing metrics. By trying to unify the metrics, we'll introduce a regression and may cause doc reflow problems. 

I agree that all new super families which are not yet released must have consistent vertical metrics.

My policy so far has been *'if the font has been released, the vertical metrics should visually match its previous release.'*. We use this rules for styles and glyphs as well :-)

**Comment by davelab6** [comment] 2017-08-04 16:32
However, asap and archivo's super family parts were just released this week, so there's not yet a lot of usage to break, and fontbakery can have a whitelist in cases where we don't want it to warn on discrepencies across families -- if we take your approach. 

I am more of the mind that inconsistent line heights across styles within a family (or within a superfamily, indeed) is a nasty bug that is worth fixing.

**Comment by Omnibus-Type** [comment] 2017-08-04 18:13
@m4rc1e If I had to establish a starting point in the matches, our priority would be to have Archivo vMetrics match those of Archivo Narrow. What do you think about this?

BTW: Regarding the next Asap update (now with 8 fonts), the same criteria apply: vMatrics should be matched between the standard version (Asap) and the condensed version (Asap Condensed):

![asapmatches-01](https://user-images.githubusercontent.com/8041808/28981170-1305505e-7927-11e7-944e-a273e24bd087.png)

**Comment by m4rc1e** [comment] 2017-08-05 08:59
@Omnibus-Type In this case, Asap condensed will inherit the vert metrics from Asap.

@davelab6 we'll roll with your proposal and see if any issues are filed.

**Comment by Omnibus-Type** [comment] 2017-08-06 14:49
@m4rc1e Please note that Asap latest version has now 8 styles (Regular, Medium, Semi Bold, Bold plus Italics). Can you update it, please? Thanks in advance.

**Comment by m4rc1e** [comment] 2017-08-06 16:08
@Omnibus-Type https://github.com/google/fonts/pull/1119

**Comment by felipesanches** [comment] 2017-11-21 19:38
None of the "super familiy"-level tests will happen prior to the upcoming release since it is not a trivial thing to implement and we're closing the release.

**Comment by felipesanches** [comment] 2018-06-26 05:37
Font Bakery version 0.4.3 will hopefully be our "super-families" release, to tackle this class of issues.

**Comment by felipesanches** [comment] 2020-02-14 05:16
Hopefully 0.4.3...

Well... actually 0.7.19! :-D

**Closed by felipesanches** 2020-02-14 05:16 UTC
Labels: P2 Important
