### ISSUE TITLE
check-ttf.py: Version string check

### ISSUE THREAD

**Issue by m4rc1e** [googlefonts/fontbakery#1385] opened 2017-06-15 09:24 UTC
We have a check which produces the following error:
```
The NAMEID_VERSION_STRING (nameID=5) value must follow the pattern Version X.Y between 1.000 and 9.999.
```

I don't mind a family being < 1.000. I understand we don't want version number like 1.230001. Can we make the range of this test go from 0.001–9.999?

**Comment by davelab6** [comment] 2017-06-15 12:21
No. I believe some systems have a problem with majorVersion numbers less than 1. However, I am not able to tell you what exactly the problem is, only that somewhere I heard users complaining about it.

**Comment by davelab6** [comment] 2017-06-15 12:22
> 1.230001

I believe that would be rounded down, to 1.123

**Comment by graphicore** [comment] 2017-06-15 12:24
>  some systems have a problem with majorVersion numbers less than 1

We need this kind of information attached to the tests. The rules we have are sometimes very obscure :-D

**Comment by felipesanches** [comment] 2017-06-15 13:47
I agree that we must gradually collect and document these descriptions of the rationale behind each of the tests.

**Comment by davelab6** [comment] 2017-07-25 00:11
@m4rc1e I believe this can be closed as I answered your question.

**Closed by davelab6** 2017-07-25 00:11 UTC
