### ISSUE TITLE
CMAP Drop specific tables

### ISSUE THREAD

**Issue by Colophon-Foundry** [googlefonts/fontbakery#1591] opened 2017-09-25 12:52 UTC
In the command:
fontbakery-fix-cmap.py

Currently only drops the tables the tables listed as PlatformID: 3
Are we able to add options to drop specific tables (e.g. PlatformID: 0)?

These are superfluous tables which in some instances (e.g. Android) that aren't needed.

**Comment by davelab6** [comment] 2017-09-25 12:56
(from phone) The pid=0 are for osx and for 3 are windows? What are the unicode ones?

**Comment by Colophon-Foundry** [comment] 2017-09-25 12:59
pid=0 – Unicode; 2.0+semantics, BMP only
pid=1 – Macintosh; Roman
pid=3 – Microsoft; Unicode BMP only

Is what's stated in OTMaster

**Comment by felipesanches** [comment] 2017-09-25 14:06
I can change the code to do these extra things. But I'd rather only do it if we get a clear rationale, otherwise I'd few a bit dumb implementing stuff blindly. I want to understand what's the real need for this. Are there user agents that fail to load a font with these tables? Or is it only meant for reducing file-size, or some other reason?

It would make me extremely happy to hear some of you explain in more details the PROs and CONs of it all.

Also, we should be collecting this kind of knowledge in general so we can better document the scripts on their respective docstrigs as well as an overview on FontBakery's README.md.

**Comment by felipesanches** [comment] 2017-09-25 14:12
I also noticed that the **-drop-mac-subtable** long argument lacks an 's' (plural) and it has only a single dash. Long attributes should have two dashes while short ones (like **-f4** and **-dm**) should have a single one. I'll change that soon to **--drop-mac-subtables** (just like **--format-4-subtables**)

And the --help output has poorly formatted info text. I'll clean that up as well.

**Comment by davelab6** [comment] 2017-09-25 22:10
The specific engineering request was, 

> If there are duplicate entries in the name with with different platform IDs, yes, please remove the Apple ones and only keep the Microsoft ones.

However, I would say we prefer Unicode ones over MS ones

**Comment by Colophon-Foundry** [comment] 2017-09-28 13:38
We were targeting Android users specifically, and found that we only needed one set of CMAP tables (Unicode, pid=0). The rest could be removed in their entirety, as this would help save on the file size.

**Comment by felipesanches** [comment] 2017-10-16 13:18
The original request in the initial description of this issue asks for a way to **(A)** "drop specific tables (e.g. PlatformID: 0)". And the latest message requests **(B)** a tool to drop all except pid=0.

Those sound like requests with completely opposite meanings. Can I move on and implement only **(B)** "drop all CMAP except pid=0" ? Or do you actually need both kinds of tool feature ?

**Comment by Colophon-Foundry** [comment] 2017-10-16 13:22
From further discussion, it turns out that pid=0 needs to be retained, and everything else can be removed as far as I'm aware. Sorry for the confusion.

**Comment by felipesanches** [comment] 2017-10-16 13:23
No problem. Thanks for the clarification. I'll be working on implementing this now.

**Comment by felipesanches** [comment] 2017-10-16 15:22
I've implemented it in the above merged pull request.

Please test it and reopen the issue is any further tweaks are needed in the tool.

cheers!

**Closed by felipesanches** 2017-10-16 15:22 UTC
Labels: P0 Urgent

**Comment by davelab6** [comment] 2017-10-16 17:56
Thanks Felipe!

**Comment by Colophon-Foundry** [comment] 2017-10-20 07:40
This is great, thanks Felipe!

**Comment by felipesanches** [comment] 2017-10-20 11:53
you're welcome! ;-)

Let me know if you need any further tweaks or fixes.

**Comment by paperboyo** [comment] 2017-12-28 00:48
Thanks for this tool!

Just in case it might be helpful to somebody (as reading just the spec hasn’t helped me much): testing on Win10, Firefox 56, Chrome 64, Opera 50 and Edge 41 are all fine with either `format-4-subtables` or `keep-only-pid-0` or both. But IE11 won’t render a font after `keep-only-pid-0`.

Admittedly, tested only on one font…

Personal takeout (original font contains just PID 0, 3): dropping v.12 to v.4 when there are no glyphs encoded outside BMP (`format-4-subtables` errors if true) saves quite a bit (>7% in my case) even in woff2, while keeping only PID 0 doesn’t save anything and is not safe. Will see how picky Safari is and report here if needed.

**Comment by davelab6** [comment] 2017-12-28 05:13
@paperboyo thanks for reporting this info, super helpful! :)
